"""Add truncate_data field to importers table

Revision ID: 7264abdb19db
Revises: f45e8c9d1234
Create Date: 2025-08-28 00:55:16.666359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7264abdb19db'
down_revision: Union[str, None] = 'f45e8c9d1234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('importers', sa.Column('truncate_data', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('importers', 'truncate_data')
    # ### end Alembic commands ###
