"""Add hashed_api_key to users table

Revision ID: afc08705fd33
Revises: c734150f184e
Create Date: 2025-08-10 00:02:59.817150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc08705fd33'
down_revision: Union[str, None] = 'c734150f184e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_jobs', sa.Column('valid_csv_path', sa.String(), nullable=True))
    op.add_column('import_jobs', sa.Column('invalid_csv_path', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hashed_api_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_hashed_api_key'), 'users', ['hashed_api_key'], unique=True)
    op.drop_constraint('webhook_events_import_job_id_fkey', 'webhook_events', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_events', 'import_jobs', ['import_job_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_events', type_='foreignkey')
    op.create_foreign_key('webhook_events_import_job_id_fkey', 'webhook_events', 'import_jobs', ['import_job_id'], ['id'])
    op.drop_index(op.f('ix_users_hashed_api_key'), table_name='users')
    op.drop_column('users', 'hashed_api_key')
    op.drop_column('import_jobs', 'invalid_csv_path')
    op.drop_column('import_jobs', 'valid_csv_path')
    # ### end Alembic commands ###
