"""Add plan_type to users

Revision ID: b8c7f4d9e120
Revises: afc08705fd33
Create Date: 2025-01-17 21:53:34.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8c7f4d9e120'
down_revision: Union[str, None] = 'afc08705fd33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First create the enum type
    plan_type_enum = sa.Enum('FREE', 'STARTER', 'PRO', 'SCALE', name='plantype')
    plan_type_enum.create(op.get_bind())
    
    # Add the plan_type column with default value 'FREE'
    op.add_column('users', sa.Column('plan_type', plan_type_enum, nullable=False, server_default='FREE'))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'plan_type')
    
    # Drop the enum type
    plan_type_enum = sa.Enum('FREE', 'STARTER', 'PRO', 'SCALE', name='plantype')
    plan_type_enum.drop(op.get_bind())
    
    # ### end Alembic commands ###