"""Add performance indexes to import_jobs table

Revision ID: e445fd7b2717
Revises: 7264abdb19db
Create Date: 2025-09-09 13:58:49.190884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e445fd7b2717'
down_revision: Union[str, None] = '7264abdb19db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_import_jobs_created_at', 'import_jobs', ['created_at'], unique=False)
    op.create_index('idx_import_jobs_status', 'import_jobs', ['status'], unique=False)
    op.create_index('idx_import_jobs_user_created', 'import_jobs', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_import_jobs_user_id', 'import_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_import_jobs_user_id', table_name='import_jobs')
    op.drop_index('idx_import_jobs_user_created', table_name='import_jobs')
    op.drop_index('idx_import_jobs_status', table_name='import_jobs')
    op.drop_index('idx_import_jobs_created_at', table_name='import_jobs')
    # ### end Alembic commands ###
